version: "3.9"
services:
  slate-db:
    image: postgres:13.2-alpine
    container_name: slate-db
    ports:
      - "65432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: slate
