version: "3.9"
services:
  slate-db:
    image: mongo:5.0.0-rc2
    container_name: slate-db
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
