version: "3.9"
services:
  slate-db:
    image: postgres:13.4-alpine
    container_name: slate-db
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB_NAME}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - slate-postgres:/var/lib/postgresql/data
  slate-sessions:
    image: redis:6.2.4-alpine3.13
    container_name: slate-sessions
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - slate-redis:/data
volumes:
  slate-postgres:
  slate-redis:
